# =========================
# DEV IMAGE (VITE)
# =========================

FROM node:23.10.0-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем только package.json и package-lock.json для кэширования зависимостей
COPY package.json package-lock.json* ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь проект (для dev-сервера)
COPY . .

# Устанавливаем Vite polling для Docker (можно и через env)
ENV CHOKIDAR_USEPOLLING=true

# Экспонируем порт Vite
EXPOSE 5173

# Запускаем dev-сервер
CMD ["npm", "run", "dev"]
